### ISSUE TITLE
closeOnEscape() with multiple windows

### ISSUE THREAD

**Issue by code-disaster** [kotcrab/VisEditor#10]
Just a minor annoyance:

- create a modal window with closeOnEscape()
- from within this window, open a FileChooser window

Now, if the escape key is pressed, the modal window closes first, and the FileChooser window stays open. On the second key press the FileChooser window closes.

I'd expect the FileChooser window closing first.

**Comment by kotcrab** [comment]
Confirmed. Happens because newly opened window does not acquire keyboard focus.
