### ISSUE TITLE
selecting an entity in a group makes the editor crash

### ISSUE THREAD

**Issue by omomthings** [kotcrab/VisEditor#101]
also can't export a scene with groups in it

**Comment by kotcrab** [comment]
Could you elaborate more? Does it happen on converted project? What type of entities and what additional components they have? Looks like grouping sprites works fine on 0.3.1-SNAPSHOT.

**Comment by omomthings** [comment]
yes it happens on a converted project, I didnt try on a new project, it's a group of simple sprites with physics component and polygon component, if i try to click on one of the sprites the editor crashes immediately, I have another group in the same scene but without physics and polygon component, selecting the works fine though..

**Comment by kotcrab** [comment]
Ok I will try it, please also pastebin/gist editor crash report. https://github.com/kotcrab/VisEditor/wiki/Locating-Log-Files

**Comment by omomthings** [comment]
ok i'll send it now, also when i try to export the scene here is what i'm told
[export crash.txt](https://github.com/kotcrab/VisEditor/files/69084/export.crash.txt)

**Comment by omomthings** [comment]
[viseditor-crash 15-12-21 22-40-59.txt](https://github.com/kotcrab/VisEditor/files/69085/viseditor-crash.15-12-21.22-40-59.txt) here is the log output

**Comment by omomthings** [comment]
I just figured out what was the problem! in the list of entities in the scene, on the left, not all entities are available, thats why it crashes.. maybe a bug during the conversion, therefor it's not really a bug on the editor!
