### ISSUE TITLE
Flip Y not always saved

### ISSUE THREAD

**Issue by omomthings** [kotcrab/VisEditor#103]
The weird thing is that some sprites with the flipped y value is correctly saved, but not for all the entities. working with the 0.3.1-SNAPSHOT

**Comment by omomthings** [comment]
Moreover, some elements with a flip Y set to false are saved with a true value, note that the entities with that problem are always the same!

**Comment by kotcrab** [comment]
It happens only with sprites right? If so, this should be fixed. This was actually fault of texture reloading not scene saving. Please confirm this fix works. Thanks!

**Comment by kotcrab** [comment]
(new editor snapshot is still building)

**Comment by omomthings** [comment]
actually I only tried with sprites so I guess that you're right, I'll wait for the snapshot and i'll confirm if it's fixed!

**Comment by kotcrab** [comment]
@omomthings any update on this one?

**Comment by omomthings** [comment]
Tried last night and everything was good!
