### ISSUE TITLE
Cancel last scale action crash

### ISSUE THREAD

**Issue by omomthings** [kotcrab/VisEditor#106]
If I scale a sprite and then I cancel the action (ctrl+Z) the editor crashes, here are some logs, (I know I gave you a lot of work tonight! :smiley: 
[viseditor-crash 15-12-22 21-33-44.txt](https://github.com/kotcrab/VisEditor/files/70238/viseditor-crash.15-12-22.21-33-44.txt)
[viseditor-crash 15-12-22 21-36-23.txt](https://github.com/kotcrab/VisEditor/files/70239/viseditor-crash.15-12-22.21-36-23.txt)
[viseditor-crash 15-12-22 21-40-07.txt](https://github.com/kotcrab/VisEditor/files/70241/viseditor-crash.15-12-22.21-40-07.txt)

**Comment by kotcrab** [comment]
Fixed, will also fix other similar issues related to undoing changes made in Entity Properties dialog.
