### ISSUE TITLE
Entity not following bounding box after undo

### ISSUE THREAD

**Issue by omomthings** [kotcrab/VisEditor#108]
I have found two ways to reproduce the issue, (therefor two slightly different issues),
First methode:
1. you create an entity and then flip it over X/Y values, 
2. suppress it 
3. ctrl+Z twice to undo suppress and undo flipping,
if you try to move the entity you should be able to move just the bounding box, not the entity..
Second:
same as first one just change the renderable value instead of flipping..
I guess that there may be other ways to reproduce it, but I think that it's related to the same problem..

**Comment by kotcrab** [comment]
Suppress is weird way of saying delete ;) I can reproduce it so I will investigate now.

**Comment by omomthings** [comment]
Hahaha yeah, polyglot problems.. :smiley:

**Comment by kotcrab** [comment]
Fixed it, also done #98 at the same time and fixed some crash when doing something like this:
1. Add Entity
2. Change any of it's property using Entity Properties
3. Remove Entity
4. Undo 3 times, redo 3 times
5. Repeat step 4 until crash.
