### ISSUE TITLE
VisUI 1.0.0

### ISSUE THREAD

**Issue by kotcrab** [kotcrab/VisEditor#115]
After over year of development VisUI will be reaching 1.0.0 version. I want to focus on cleaning up the API. Here's a list of things I gathered to do for now:

* [x] Move `InputValidator` to util package
* [x] Rename `DialogUtils` to `Dialogs`
* [x] `ErrorDialog` renamed to `DetailsDialog`
* [x] Refactor `FileChooserListener` `selected(File)` and `selected(Array)` methods
* [x] USL in Maven Central
* [x] Check styles name for consistency
* [x] Need to check up `TabbedPane` vertical mode
* [x] Refactor `Tooltip` constructors
* [x] Move I18N bundle management to `Locales`

#####  New features
* [x] LibGDX 1.9.2
* [x] ListView - similar to Android ListView's
* [x] `ButtonBar` - allows to easily create table with buttons like "Ok", "Cancel", "Yes", "No" in platform dependentant order, see JavaFX's [ButtonBar](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/ButtonBar.html).
 * [x] `Dialogs` refactored to use `ButtonBar`
* [x] Flow laytous
* [x] Resizeable window style
* [x] Use system cursors

##### Other
* [x] Check if GWT still works

#####  Update wiki
Don't update existing pages before 1.0.0 release.
* [x] FileChooser - listener section
* [x] ListView
* [x] ButtonBar
* [x] FlowGroups
* [x] Tooltips - add `TooltipBuilder`
* [x] I18N

If you have any suggestions please leave your comment here.

**Comment by intrigus** [comment]
How exactly will ListView differ from a ScrollPane with a table inside? What's the purpose of ListView?

**Comment by kotcrab** [comment]
It would be similar to Android list system, more flexible than putting table inside ScrollPane. This was suggested somewhere in comments on website so I haven't thought that much about it yet.

**Comment by czyzby** [comment]
Horizontal and vertical flow layouts, keeping all widgets within a chosen width/height and appending actors to the next row/column if they don't fit. Optional settings for fixed width and height of actors. This would allow to simulate browser-like tab pane.

**Comment by xeoshow** [comment]
+1 for the flexiable and powerful ListView ! ...

**Comment by xeoshow** [comment]
Hopefully the ListView could have the header,footer disign, and alphabet listview ...

**Comment by kotcrab** [comment]
@xeoshow ListView is done if you want to take a look. See [TestListView](https://github.com/kotcrab/VisEditor/blob/master/UI/test/com/kotcrab/vis/ui/test/manual/TestListView.java).

**Comment by ShibaBandit** [comment]
I don't see FileChooser#listener getting used anymore?

**Comment by ShibaBandit** [comment]
Actually... I see in FileChooser possibly bad inequality - 

		if (files.size == 0) {
			listener.selected(files);
		}

I think it needs to be files.size != 0

**Comment by kotcrab** [comment]
@ShibaBandit yeah, you are right, I changed it. Thanks.

**Comment by kotcrab** [comment]
All done and 1.0.0 released: http://kotcrab.com/blog/2016/02/13/visui-100-released/
