### ISSUE TITLE
How can I use the findActor or stage related things in VisRuntime?

### ISSUE THREAD

**Issue by xeoshow** [kotcrab/VisEditor#117]
Hi,

Just new to Vis, is there any way I can use stage related things in Vis? Currently seems it is heavily dependent on the Sprite related things, but looks like findActor and addListener is quite good for me, not sure is there any way to do this?

By this way, I think it is easy to create Actor during runtime and use them. Thanks!

**Comment by xeoshow** [comment]
Hopefully there could be more demo usage for every UI component.

**Comment by kotcrab** [comment]
VisRuntime doesn't use stage2d at all so you can't use any of scene2d features. VisRuntime uses entity-component-system design. Those two can't be directly mixed. If you want to create game UI with scene2d.ui you will have to create sceen2d elements from code.

Yes, creating Actor is easy but Actor is part of scene2d, like I said it can't be easily and directly used with ECS framework.

Also this is an issue tracker, in the future please use [forums](http://forum.kotcrab.com/) or our [IRC](https://github.com/kotcrab/VisEditor/wiki/IRC-Channel-and-Forum) for such questions, thanks.
