### ISSUE TITLE
LibGDX html error / missing artemis dependency

### ISSUE THREAD

**Issue by slajar** [kotcrab/VisEditor#118]
I should report the issue here:
see https://github.com/libgdx/libgdx/issues/3737

VisRuntime extension depends on artemis and doesn't declare this dependency

**Comment by kotcrab** [comment]
Show your `build.gradle` but probably you are missing `artemis-odb-gwt`. See https://github.com/kotcrab/VisEditor/wiki/LibGDX-Project-Setup

**Comment by kotcrab** [comment]
Looks like it's resolved so I'm closing this. I also submitted patch to libgdx that allows to declare external dependencies so now new projects with VisRuntime will work out of the box.
