### ISSUE TITLE
Unable to see folders in File Chooser

### ISSUE THREAD

**Issue by StrongJoshua** [kotcrab/VisEditor#12]
If I use the filechooser I can only see allowed files (those that the file filter returns true for), but I also cannot see any directories.
This is what one of my FileFilters looks like:
```java
fileChooser.setFileFilter(new FileFilter() {
					@Override
					public boolean accept (File pathname) {
						return pathname.getPath().endsWith(".rbm") || pathname.isDirectory();
					}
				});
```
I thought at first that they weren't showing because my file filter did not return true for directories, but I changed it (as you can see) and they still won't show up.

The file chooser's selection mode is files, but even if I change it to files and folders I still cannot see any folders.

**Comment by kotcrab** [comment]
Works for me, both txt files and folders are showed, tested on latest snapshot.
```java
FileChooser chooser = new FileChooser(Mode.OPEN);
chooser.setSelectionMode(SelectionMode.FILES);

chooser.setFileFilter(new FileFilter() {
	@Override
	public boolean accept (File pathname) {
			return pathname.getPath().endsWith("txt") || pathname.isDirectory();
	}
});
```

**Comment by kotcrab** [comment]
Isn't it related to #6 ?

**Comment by StrongJoshua** [comment]
Omg, I'm dumb. I forgot to add the check for directories for one of my buttons' file filters :3
But yeah, without having the filter return true for directories, they are invisible. I don't know if you want to keep this as a feature, but my issue is resolved.

**Comment by kotcrab** [comment]
Filter is used directly in `file.list(filter)` method from GDX, so it's not possible to add more conditions to it. I could create some multiplexer but it's overkill imho.
