### ISSUE TITLE
Get rid of most parts using java.awt.*

### ISSUE THREAD

**Issue by intrigus** [kotcrab/VisEditor#123]
We can't use AWT and LWJGL3 on Mac.
That's why we have to get rid of calls to awt.
- [x] https://github.com/kotcrab/VisEditor/blob/b2ea63a045e805099ddd16778517d46d2419a637/Editor/src/com/kotcrab/vis/editor/module/editor/MouseLoopingModule.java

(Can maybe implemented using LWJGL3?)
- [x] https://github.com/kotcrab/VisEditor/blob/b2ea63a045e805099ddd16778517d46d2419a637/Editor/src/com/kotcrab/vis/editor/util/FileUtils.java

(Can be replaced by http://www.coderanch.com/how-to/javadoc/appledoc/api/com/apple/eio/FileManager.html#revealInFinder(java.io.File) )
- [x] https://github.com/kotcrab/VisEditor/blob/6922453a3d96b8087540cccb352a3483c7676649/UI/src/com/kotcrab/vis/ui/widget/file/internal/FilePopupMenu.java

(Can be replaced by http://www.coderanch.com/how-to/javadoc/appledoc/api/com/apple/eio/FileManager.html#revealInFinder(java.io.File) )

Other parts that use ```java.awt.Color```, ```java.awt.Graphics2D``` or ```java.awt.image.BufferedImage```can be safely used if we set awt to headless mode.

Libgdx includes AppleJavaExtensions this way https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl3/pom.xml#L60-L67

**Comment by kotcrab** [comment]
Thanks for the summary.

* `MouseLoopingModule` - I don't think it can be done using LWJGL3, if you are sure that AWT `Robot` doesn't work on Mac then this feature won't be supported on OSX.
* I need confirmation that `Desktop.getDesktop().edit(...)` is not supported, looks like `FileManager` does not support this but [this](http://stackoverflow.com/questions/526037/how-to-open-user-system-preferred-editor-for-given-file/526069#526069) is possible workaround.
* FilePopupMenu is fixed

**Comment by kotcrab** [comment]
`Desktop.getDesktop().edit(...)` is not supported and was replaced by `Runtime.getRuntime().exec("open filename")` on Mac.

**Comment by kotcrab** [comment]
Should be all, closing.
