### ISSUE TITLE
Created a folder that can not be deleted

### ISSUE THREAD

**Issue by xtremetom** [kotcrab/VisEditor#125]
The output folder Im using did work once. Today the gfx folder contained within lost its owner as consequently cannot be deleted, edited or have any data written to it.

I have tried pretty much everything short of formatting my hd :)

https://gyazo.com/295f5607193b2611cd08c096d919f73b

**Comment by kotcrab** [comment]
This seems to be unrelated to VisEditor, something is wrong with your file permissions. Maybe some hard drive issues? Can you reproduce this or did it just happen once? I'm not able to fix it or even investigate without way to reproduce it.

**Comment by xtremetom** [comment]
I thought that but it only occurred when I tried to export my project.

**Comment by kotcrab** [comment]
Still, without way to reproduce it's not even possible to classify it as a VisEditor bug. VisEditor uses standard Java APIs to delete or create files so it's very unlikely that problems lies here. I would suspect something is wrong on your end.

**Comment by xtremetom** [comment]
Ok thanks. If it repeats Ill let you know just incase
