### ISSUE TITLE
editor.requestExit() not called when closing the editor frame

### ISSUE THREAD

**Issue by SaeedMasoumi** [kotcrab/VisEditor#130]
Hi,
When i close VisEditor with close button in window decoration, it doesn't call [dispose() ](https://github.com/kotcrab/VisEditor/blob/master/Editor/src/com/kotcrab/vis/editor/Editor.java#L255) method nor show a "confirm exit" dialogue. 

But when i go to file->exit button, it works properly. 

I think the problem is here
https://github.com/kotcrab/VisEditor/blob/master/Editor/src/com/kotcrab/vis/editor/ui/EditorFrame.java#L164

**Comment by kotcrab** [comment]
That's interesting. Looks like the LWJGL Timer thread is created only on Windows. I'll search for some other method. Thanks for reporting.
