### ISSUE TITLE
How can I get the UI component Object reference via code if using USL?

### ISSUE THREAD

**Issue by xeoshow** [kotcrab/VisEditor#133]
Hi,

I have registered at forum.kotcrab.com, but seems still can not post things, so write it here:

I am new to Vis, and now trying to use USL file to define the UI, if in the USL I have a component and want to add listener to it via code, how can I get the UI component Object reference?

Thanks!

**Comment by kotcrab** [comment]
I can see your account in db and it's activated so you should be able to post things normally, please contact me on email if it still persists.

USL is just a JSON with some fancy features, ultimately it's converted to JSON so I will just talk about JSON but it's also applies to USL.

I think you are confusing two things here. In case of scene2d.ui in JSON file is only used to define how widgets looks, eg. what drawables they will use for background, what font will be used etc. Essentially you are defining look styles there.

From what I understand you are trying to define your UI layout in JSON. This is not possible in scene2d.ui although there is [gdx-lml](https://github.com/czyzby/gdx-lml) and it's VisUI extension: [gdx-lml-vis](https://github.com/czyzby/gdx-lml-vis) which allows to do it via html like syntax.

Also take a look at https://github.com/libgdx/libgdx/wiki/Scene2d.ui and https://github.com/libgdx/libgdx/wiki/Skin, hope that clears things out. I'll close this but fell free to ask if you have any more questions.
