### ISSUE TITLE
Local install with gradle not possible

### ISSUE THREAD

**Issue by Favorlock** [kotcrab/VisEditor#137]
After some recent changes building to local maven repo has issues.

FAILURE: Build failed with an exception.

* What went wrong:
Unable to retrieve secret key from key ring file 'E:\development\projects\other\VisEditor\runtime\PathToYourKeyRingFile' as it does not exist

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by Favorlock** [comment]
So a temporary solution is to add "-x signArchives" as a script parameter in IntelliJ. Would be nice to find a way to disable signArchives whenever it is not needed, otherwise a note should be very clearly visible on github documentation.

**Comment by kotcrab** [comment]
Thanks, `required { isReleaseVersion && gradle.taskGraph.hasTask("uploadArchives") }` is not enough, signing is always performed when possible so I also have commented out the signing settings in `gradle.properties`.
