### ISSUE TITLE
TabbedPane: tabsTable is added to the mainTable on the left, not the top-left

### ISSUE THREAD

**Issue by Portals** [kotcrab/VisEditor#20]
As you can see [here](https://github.com/kotcrab/VisEditor/blob/master/UI/src/com/kotcrab/vis/ui/widget/tabbedpane/TabbedPane.java#L89), the tabsPanel is added to the left, not the top left. Which makes the following result: http://imgur.com/flZxA94.

**Comment by Portals** [comment]
Sorry, was doing it wrong! :(

**Comment by kotcrab** [comment]
You have to do expandX().fillX() when adding TabbedPane, I guess I can change tabsPanel to expandX but it still would be affected by table you are adding pane to.
