### ISSUE TITLE
Needed add robovm.xml property for reflection

### ISSUE THREAD

**Issue by mtsr** [kotcrab/VisEditor#33]
Currently getting reflection error unless I add the following to my robovm.xml file.

    <forceLinkClasses>
      <pattern>com.kotcrab.vis.ui.widget.**</pattern>
    </forceLinkClasses>
  
Could you add this to the read me? On IRC it's suggested that an included robovm.xml file in the project would get merged, so people wouldn't even need to add this.

**Comment by kotcrab** [comment]
I added robovm.xml, could you try 0.8.2-SNAPSHOT and confirm that it works?

**Comment by kotcrab** [comment]
Confirmed to work.
