### ISSUE TITLE
Remove workaround when Artemis has been fixed

### ISSUE THREAD

**Issue by kotcrab** [kotcrab/VisEditor#34]
Undo 40ef2fe51961a753e56806b0def43a31318aab30 after https://github.com/junkdog/artemis-odb/issues/347 is fixed.

**Comment by junkdog** [comment]
0.13.0 is out, with included fix.

**Comment by kotcrab** [comment]
That was quick, thanks!

**Comment by junkdog** [comment]
don't like having lingering bugs in the latest release ;)
