### ISSUE TITLE
A means to stop editing on VisTextField (or stopping a text field from capturing key events)

### ISSUE THREAD

**Issue by adam-law** [kotcrab/VisEditor#39]
Hi,

There is no way to make a text field stop editing, thus making it stop capturing all key events. 

I've set all of my text fields to use a custom input processor, tried overriding keyUp, keyDown, and keyTyped so that I can return false on these, used FocusManager.getFocus() and FocusManager.getFocus(anotherWidget) {seems losing focus doesn't stop it from receiving key events}.

I use an InputMultiplexer and have my Scene2d/VisUI stuff as the 1st entry, otherwise, my main canvas gets all the events before the HUD/ GUI overlay; but when it's set this way, and a text field was focused, it will capture all key events from that point on.

Thanks.

**Comment by intrigus** [comment]
Have you verified that this works with a normal TextField?
Why do you think that this is a VisUI  hug?

**Comment by adam-law** [comment]
This is actually a feature request. I don't think it's a bug per se. It's simple enough to test. Just have a text field in a stage that is the first entry in a InputMultiplexer. Once it has been used, it captures all key events, even if the focus is taken away via FocusManager.get(). Of course, when another Scene2dUI / VisUI components gets focus, there's no problem, they take over and capture key events properly, as is expected since they're delegates in the same stage. The problem is with non-Scene2DUI input processors in the multiplexer that also need to receive key events.

Using a custom input processor and returning false on all key-related event handlers, does nothing. From what I've read TextFields are a special case.

**Comment by kotcrab** [comment]
Simply call `stage.setKeyboardFocus(null)`. FocusManager is used only for managing widgets focus borders rendering.

**Comment by adam-law** [comment]
awesome. I'll give it a spin. many thanks.

**Comment by intrigus** [comment]
Could you post a http://sscce.org/ ?

**Comment by kotcrab** [comment]
@intrigus what's the reason for that? there isn't any issue

**Comment by kotcrab** [comment]
@adam-law Don't edit your posts, nobody gets notified if you do so.

It's all about focus, once you set stage keyboard focus back to null, text field won't process any events and will return false, so events will be delegated further: https://github.com/kotcrab/VisEditor/blob/master/UI/src/com/kotcrab/vis/ui/widget/VisTextField.java#L966. If you can reproduce it with standard TextField then it's a LibGDX issue otherwise please create [SSCCE](http://sscce.org/).

**Comment by adam-law** [comment]
sorry kotcrab. old habits from another project. it won't happen again. I should have read your earlier post more clearly, I thought you meant setting the stage's keyboard focus to null at creation. I get now you meant after the key event, in place of the FocusManager method I called by mistake. 

It now works as I wanted it too. Thanks!
