### ISSUE TITLE
Tooltip isn't removed properly inside ChangeListener

### ISSUE THREAD

**Issue by nikoliazekter** [kotcrab/VisEditor#41]
I get ```java.lang.IllegalStateException: More than one tooltip cannot be added to the same target!``` when I'm using this code inside button ChangeListener:
```
Tooltip.removeTooltip(pauseResumeButton);
new Tooltip(pauseResumeButton, "Resume (P)");
```

**Comment by kotcrab** [comment]
All actors use DelayedRemovalArray for listeners. Listeners cannot be changed when events are being processed, there isn't anything I can do about it. Though there isn't need to create new tooltip, you can do `tooltip.setContent(...)` or if you are using text tooltip do `tooltip.getContent()` cast it to VisLabel and change text.

**Comment by nikoliazekter** [comment]
Thanks now it works as I want. I also had to call ```tooltip.pack()```.

**Comment by kotcrab** [comment]
Now pack is always called after changing tooltip content.
