### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by mlipmanx** [kotcrab/VisEditor#44]
1. Create a layer to simplify the .JSON files - currently they are tied to VisUI. What I think you need is to create some "struct" type classes that only contain the datafields you need to build the sprite, etc. For example:
class spriteJson
{
      float x,y;
      float width, height;
      String id;
      <etc>
}
This will allow easier building of scenes without using VisUI - for example, custom Scene2d setups

2. Allow object bounds to be changed - not just the scale. ideally by dragging corners

**Comment by kotcrab** [comment]
1. Not sure what JSON files you mean. In project, editor doesn't store scene in JSON but in binary format using Kryo. Though I intend to change this in VisEditor 0.3.0 so it would be possible to edit scenes as text file or for easier working with VCS. If you mean the exported JSON files that is already done, nothing more is stored than to eg. build a sprite. Why do you think they would be tied to VisUI?
2. Created #47 for this feature request

**Comment by mlipmanx** [comment]
Sorry, I was a bit unclear.

I was talking about the .scene exported files. It would be nice if there
was some way of reading the scene files into a typed data structure - with
no other functionality, so you could use that to populate the scene.

(a bit like JAXB does for XML)


Am I making sense?


Thanks



Mark


PS: I love your editor - it is the best

**Comment by kotcrab** [comment]
You can do it now. It's possible to deserialize scene file into [SceneData](https://github.com/kotcrab/VisEditor/blob/master/Runtime/src/com/kotcrab/vis/runtime/data/SceneData.java) object, checkout [this](https://github.com/kotcrab/VisEditor/blob/master/Runtime/src/com/kotcrab/vis/runtime/scene/SceneLoader.java#L141-L142). You will get entire scene structure without need to load anything.

**Comment by mlipmanx** [comment]
Thanks Pawel, that's exactly what I was looking for.

Is there any way to add a "Tag" to a component? That would be useful, for
example to indicate a custom class should be instantiated


Thanks

**Comment by kotcrab** [comment]
You can configure JSON to instantiate some different class, like [here](https://github.com/kotcrab/VisEditor/blob/master/Runtime/src/com/kotcrab/vis/runtime/scene/SceneLoader.java#L88-L116). Of course that class would have to be compatible with original.

**Comment by mlipmanx** [comment]
Hi Pawel,

Yes, that's what I was thinking - but I would need a tag to work out which
class to instantiate - ie in the editor, it might be an image, but I want
to replace it with a button, or something else.


Regards


Mark

**Comment by kotcrab** [comment]
I see, that's not possible now. You can add `VariablesComponent` to Entity and then read them and transform Entity into something else but you can't skip default loading. I'm thinking of adding component that will cause to skip default entity loading (ie. creating `SpriteComponent` from `SpriteProtoComponent`) so you could manually handle such entity.

**Comment by mlipmanx** [comment]
Hi Pawel,

Actually, I think VariablesComponent will solve my issue.


Thanks


Mark

**Comment by mlipmanx** [comment]
Hi Pawel,

If you add a variablesComponent, it is impossible to set the "Values" in
the editor - a bug


Regards


Mark

**Comment by kotcrab** [comment]
In "Add..." field you need to type key name and press enter, then you can set value.

**Comment by mlipmanx** [comment]
Yes, but then when you type in the value field, nothing appears


Thanks

**Comment by kotcrab** [comment]
Works for me, are you using 0.2.5?

**Comment by mlipmanx** [comment]
Yes, on Linux

It almost seems to lose focus from the field.

Is there a log or something I can send you?


Regards


Mark

**Comment by kotcrab** [comment]
Fixed it, you will have to use cutting edge build: http://dl.kotcrab.com/vis/editor/edge/VisEditor-edge-20151011-1.zip

Btw please use our [forums](http://forum.kotcrab.com) next time for such discussions, thanks.
