### ISSUE TITLE
VisUI: default text or selection for InputDialog and FileChooser

### ISSUE THREAD

**Issue by code-disaster** [kotcrab/VisEditor#45]
Some ideas for [optional] convenience functions:

- InputDialog: Initial input text. Should be preselected/highlighted so that user can decide to overwrite, or edit easily. Also, it'd be nice to auto-focus the input field when showing the dialog.

- FileChooser: in file mode, have an option to preselect an existing file. Or, in save mode, to write a predefined file extension to the input field.

**Comment by kotcrab** [comment]
InputDialog changes are done.

Not sure what do you mean about writing predefined extension to field, what would that do?

**Comment by kotcrab** [comment]
Added method to set selected files in chooser, though there's one flaw I couldn't make file list scroll pane to scroll to that file. I can't get proper coordinates of FileItem [here](https://github.com/kotcrab/VisEditor/blob/master/UI/src/com/kotcrab/vis/ui/widget/file/FileChooser.java#L659). localToParent(Stage)Coordinates returns very weird cords.

**Comment by code-disaster** [comment]
> Not sure what do you mean about writing predefined extension to field, what would that do?

The scenario in our work-in-progress editor: I want to save a file in JSON format, so I open FileChooser with a certain folder and the filter set to .json. But still, the user would need to type "filename - dot - json". The idea is to preset the input field to ".json".

Now as I think of it, I may also expand our own code to conditionally append the extension myself... :)

Thanks a lot for the other changes.

**Comment by kotcrab** [comment]
Imo having just the extension already in field seems a bit unintuitive. User would have to click at begging of field to use it, if he clicked somewhere else then he needs to use arrow keys to move at begging or erase text and retype it. Kinda bad UX, I'd leave that for now ;)
