### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by halfnelson** [kotcrab/VisEditor#48]
I tested the tool and wanted to use it for a non libgdx project. Unfortunately it does not output in JSON but some weird json like format where the keys and string values are not quoted. Is it possible to output in real JSON?

**Comment by kotcrab** [comment]
Not yet, I will add that as option for exporter.

**Comment by kotcrab** [comment]
Done, to use normal JSON format, go to Settings -> Export, press Settings button and uncheck "Use minimal output type"
