### ISSUE TITLE
Alignment has no effect on PopupMenu

### ISSUE THREAD

**Issue by nikoliazekter** [kotcrab/VisEditor#52]
I can't position PopupMenu with setPosition(x, y, Align.topLeft) to make its top left corner be at (x,y). Maybe that's not the right way to do it but what is the right one? Wiki doesn't mention it.

**Comment by kotcrab** [comment]
Works for me.
```java
PopupMenu m1 = new PopupMenu();
m1.addItem(new MenuItem("A1"));
m1.addItem(new MenuItem("B1"));
m1.addItem(new MenuItem("C1"));

PopupMenu m2 = new PopupMenu();
m2.addItem(new MenuItem("A2"));
m2.addItem(new MenuItem("B2"));
m2.addItem(new MenuItem("C2"));

m1.setPosition(100, 100);
m2.setPosition(100, 100, Align.topLeft);
stage.addActor(m1);
stage.addActor(m2);
```

![2015-10-20_1735](https://cloud.githubusercontent.com/assets/4594081/10612418/0cd27ad8-7751-11e5-8d64-2890fa4693ef.png)

Both `setPosition` methods are defined in actor, I don't know why it wouldn't work. You should create [SSCCE](http://sscce.org/)

**Comment by nikoliazekter** [comment]
Ha! It didn't work for me because I was positioning PopupMenu before adding any items to it. I just swapped some code and now it works.

**Comment by kotcrab** [comment]
SetPosition with alignment uses widget width and height so that's why it won't work before adding items, size is unknown at that point. Nothing can be done with this.
