### ISSUE TITLE
Little (secondary) ideas

### ISSUE THREAD

**Issue by omomthings** [kotcrab/VisEditor#57]
Hello, honestly I don't know if this is the right place to post this but I didnt find a better place, here are some very little ideas you could try add to the editor, none is really important in any but it may improve the editor experience:
*Drag the mouse + shortcut to rotate/scale on the go;

*Add another shortcut to do rotate/scale by steps (eg. rotate by steps of 45°, scale by steps of 0.2 etc);

*Make some primitive entities (square/circle/path) that are not graphical but have a logical meaning in the game (eg. path that an enemy will follow, an area where you enters and make's something move/fall/sound/open another thing or any other logical meaning you can find..)

*Could load a physical shape from an existing shape descriptor like a json file, eg. a json file generated by another associated physics editor ( like this simple and good <a href="http://www.aurelienribon.com/blog/projects/physics-body-editor/">Physics body editor</a> that saves the shape in a json format, ideally make the physic editor open inside visEditor/ integrate a similar technology to auto trace shape;

That's all I have for now! Have a good day and keep working on that great and promising editor! 

P.S: while i'm in the issue tracker, the editor crashes when you try to put a physical properties component.

**Comment by kotcrab** [comment]
Hi. Thanks for suggestions. Well this would be more appropriate for the forums but you know it's not big deal :)

> *Drag the mouse + shortcut to rotate/scale on the go;

I assume you mean gizmos, if so there already is #47

>*Add another shortcut to do rotate/scale by steps (eg. rotate by steps of 45°, scale by steps of 0.2 etc);

This requires gizmo's first but that's good idea. Like holding shift to make it snap to 45° etc, should be also configurable.

>*Could load a physical shape from an existing shape descriptor like a json file, eg. a json file generated by another associated physics editor ( like this simple and good Physics body editor that saves the shape in a json format, ideally make the physic editor open inside visEditor/ integrate a similar technology to auto trace shape;

Fun fact: auto tracing code is already there but needs exposure in GUI. Created #58 for that.

>P.S: while i'm in the issue tracker, the editor crashes when you try to put a physical properties component.

This deserves separate issue to be honest :D Create separate issue, include log file and write some more details.

**Comment by kotcrab** [comment]
Ops, forgot to address one thing:
>*Make some primitive entities (square/circle/path) that are not graphical but have a logical meaning in the game (eg. path that an enemy will follow, an area where you enters and make's something move/fall/sound/open another thing or any other logical meaning you can find..)

I agree on that, I'll think something about it.

**Comment by omomthings** [comment]
ok, you're right, and for the little bug i found that it was already fixed on the version 0.2.6 snapshot so no need to send an issue (I was talking about physic properties on particles)
