### ISSUE TITLE
PolygonComponent shape autotracing

### ISSUE THREAD

**Issue by kotcrab** [kotcrab/VisEditor#58]
Tracing code is already there, needs GUI dialog.

**Comment by omomthings** [comment]
working on visEditor 0.2.6 snapshot (08/11) if i add polygon component to an entity, it is drawn at unusual place when loading scene.. here is an example..
![sans titre](https://cloud.githubusercontent.com/assets/13408887/11105471/d52381d6-88c6-11e5-9afe-8c223dd3321d.png)

**Comment by intrigus** [comment]
Looks like the rotation of the objects is missing.

**Comment by kotcrab** [comment]
@intrigus yep :D

@omomthings fixed, you will need to update Runtime to 0.2.6-SNAPSHOT. Next time please create separate issue, thanks!
