### ISSUE TITLE
project asset files deleted when exporting scene

### ISSUE THREAD

**Issue by omomthings** [kotcrab/VisEditor#59]
the title said it all, when you export a scene the whole assets folder of your project is replaced by a new one containing only visEditor elements, so if you don't have a backup you lose all your project assets..

**Comment by kotcrab** [comment]
That's true. It's explicitly mentioned in project creator that assets are cleared on each export. Also when creating libGDX type project, editor copies original resources from `android/assets` to `vis/assets`. And when creating generic project asset folder must be empty otherwise you won't be able to create project.

Do you suggest any additional things to add/change?

**Comment by omomthings** [comment]
ok but if you have files like this android/asset/myFile.xml for example the file is no restored when exporting scene, at least should pop a warning about it, although i don't exactly see why assets are moved when it could just add exported elements to android/assets but i guess that it's in relation with the internal structure of the editor

**Comment by kotcrab** [comment]
Actually it's possible that files not inside any dir (eg. `vis/asset/myFile.xml`) are not copied, it should work when it in it's some dir, eg. `vis/asset/directory/myFile.xml`. I'll need to check that.

>although i don't exactly see why assets are moved when it could just add exported elements to android/assets

It's generally safer this way, it prevents situations when user file would be replaced by export, also file formats in `android/asset/scene` and `vis/asset/scene` are completely different so it wouldn't be possible to keep them in one directory.

I think I will add warning dialog before doing export and there will be option to "never show it again".

**Comment by omomthings** [comment]
ok you're the boss! and i have already tried when the file is in a directory under vis/assets it works.

**Comment by kotcrab** [comment]
Alright, we now have fancy dialog before export:
![2015-11-17_2050](https://cloud.githubusercontent.com/assets/4594081/11222919/771ae4de-8d6d-11e5-8e58-5a8d911cbf6f.png)

And files inside `vis/assets` but not in directory are now copied during export as well ;)
