### ISSUE TITLE
TextEntity zIndex always 0

### ISSUE THREAD

**Issue by UvarovBoris** [kotcrab/VisEditor#60]
Can't change set ZIndex of TextEntity in VisEditor. It is always 0.

**Comment by omomthings** [comment]
What version of visEditor are you using? on 0.2.6 snapshot i have no problem modifying it.. (although if it seem's to dont change much in the scene)

**Comment by kotcrab** [comment]
This was fixed in https://github.com/kotcrab/VisEditor/commit/94eb1b64b6955e0dd4b7dedc887330d5297544db, please try [0.2.6 snapshot build.](http://dl.kotcrab.com/vis/editor/edge/ ).

@omomthings it changes z order, to notice change you need 2 entities on same layer and they must be overlapping

**Comment by UvarovBoris** [comment]
Hi, thanks for answer, can anybody explain what I see in this directory [0.2.6 snapshot build](http://dl.kotcrab.com/vis/editor/edge/)? Is this all VisEditor 2.6.0 and I just must download last file?

**Comment by omomthings** [comment]
Yes those are the different snapshots, day by day.. I use the version of 8/11 and its enough stable. Just download it and thats all. :-)

**Comment by kotcrab** [comment]
Exactly as @omomthings said, those are built after every commit, you just need the latest one. Sorry for not explaining it.

**Comment by UvarovBoris** [comment]
All clear, thanks.
