### ISSUE TITLE
Problem of rotation on polygons

### ISSUE THREAD

**Issue by omomthings** [kotcrab/VisEditor#64]
Back in the issue #58 , the problem of sprites rendered without angles, after the fix now it's the polygon component that are no longer set with a correct angle
![sans titre](https://cloud.githubusercontent.com/assets/13408887/11143287/e0664bd4-89eb-11e5-9835-ff9e508f7e73.png)

**Comment by kotcrab** [comment]
Sorry, my fault :/. Should be working now.

**Comment by omomthings** [comment]
Under visRuntime 0.2.6-SNAPSHOT the problem persists..

**Comment by kotcrab** [comment]
Have you refreshed dependencies? Make sure that it actually downloaded latest one and note that it takes about 10 minutes after deploying for snapshot be available.

**Comment by omomthings** [comment]
yes I have already refreshed dependencies (even made a downgrade to 0.2.5 then an upgrade ) but still, then i'll wait a little while before retying. Thank you

**Comment by kotcrab** [comment]
Downgrading to 0.2.5 then again to 0.2.6-SNAPSHOT may not help, Gradle may still use cached snapshot jar. Easy check is to open one of runtime source file and check if it matches change code or try to some new class. In this case you can see if class `PhysicsSpriteComponent` exists. If it does you have the latest one and this problem still isn't fixed.

**Comment by omomthings** [comment]
No i don't have it, i'll try to re-refresh dependencies

**Comment by omomthings** [comment]
I confirm, everything works fine now! thank you
