### ISSUE TITLE
Allow to remove items from recent project list

### ISSUE THREAD

**Issue by kotcrab** [kotcrab/VisEditor#67]

**Comment by StQuote** [comment]
I'm trying to add remove buttons for 'Recent Project' list and I want to show some variants for UI. Also I want to add 'Clear list' label at the end of the list, for remove all projects from the list.

First variant is just labels without any alignment (default)
![label_center_aligment](https://cloud.githubusercontent.com/assets/4688310/11761168/9cb48e7a-a0c8-11e5-8ac6-c55ccaf86ddd.png)

Second variant is labels with left alignment
![label_left_aligment](https://cloud.githubusercontent.com/assets/4688310/11761169/a27dabb6-a0c8-11e5-9a80-55655d5d0cc9.png)


Third variant is button without alignment for project name label
![button_label_center_aligment](https://cloud.githubusercontent.com/assets/4688310/11761159/1e7bc924-a0c8-11e5-87d1-28272344d999.png)

And fourth variant is button with left alignment for project name label
![button_label_left_aligment](https://cloud.githubusercontent.com/assets/4688310/11761171/aa13da58-a0c8-11e5-9d87-f6266ab3a2e7.png)

Let me know if is there some better solutions.

**Comment by kotcrab** [comment]
Fourth looks nice, I would also remove background drawable from close
button (so only X icon is visible), over and and down drawable should be
left. I also have one suggestion, all those buttons kinda clutter UI, it
would be nice if X button would only appear if you hover mouse over project
name.

sob., 12 gru 2015, 10:11 Pavel Puchok użytkownik <notifications@github.com>
napisał:

**Comment by StQuote** [comment]
How I can remove background for up button state? This is can be done without change uiskin?

I found some places where background of up state is not visible (for ex: toolbar icons), but in all this places background of parent has the same color with up state of buttons. So is invisible just for this reason.

**Comment by kotcrab** [comment]
Something like this should work:
```java
VisImageButtonStyle style = new VisImageButtonStyle(VisUI.getSkin().get("close", VisImageButtonStyle.class));
style.up = null;
add(new VisImageButton(style));
```

**Comment by StQuote** [comment]
This works, but button begin jumping under mouse cursor. 

It seems like button in Up state have different size with Over/Down states. While state changes from Up to Over, "X" icon moved little bit to right and up, also all parent table cells change own sizes.

**Comment by kotcrab** [comment]
I see, well then don't add it. It will probably require new drawables so I'll play with it once it's merged.

**Comment by kotcrab** [comment]
Style fixed, all done.
