### ISSUE TITLE
Improve rectangular selection

### ISSUE THREAD

**Issue by kotcrab** [kotcrab/VisEditor#84]
When selecting from left to right check if object is contained fully inside selection. When selecting from right to left check if object overlaps with selection. Different selection mode should have different color. Eg. blue/green.

**Comment by kotcrab** [comment]
Hey, @StQuote want to try do this? I can give you some tips if needed. See [RectangularSelection](https://github.com/kotcrab/VisEditor/blob/editor-nxt/Editor/src/com/kotcrab/vis/editor/module/scene/entitymanipulator/RectangularSelection.java) class for starting point.

**Comment by StQuote** [comment]
Yeah, sure I can try to do this. But at the weekdays I do not have much free time, so it can be a slowly.

**Comment by StQuote** [comment]
So my results. 

From left to right gesture (red arrow painted just to show gesture):
![from_left_to_right_selection](https://cloud.githubusercontent.com/assets/4688310/11788689/6633fb24-a2a3-11e5-8d9e-e650425800b7.png)
Result:
![from_left_to_right_result](https://cloud.githubusercontent.com/assets/4688310/11788703/78c7e408-a2a3-11e5-9c3b-9e471d621256.png)

From right to left gesture:
![from_right_to_left_selection](https://cloud.githubusercontent.com/assets/4688310/11788709/821bd744-a2a3-11e5-8738-eee397a4e226.png)
Result:
![from_right_to_left_result](https://cloud.githubusercontent.com/assets/4688310/11788718/8b4237a0-a2a3-11e5-9923-3e598d297dc8.png)

Let me know if you have any comments or remarks. After you review I make PR.

**Comment by kotcrab** [comment]
Awesome, exactly what I expected, waiting for PR ;)

**Comment by kotcrab** [comment]
Merged, thanks!
