### ISSUE TITLE
Error during load atlases from subdirectories

### ISSUE THREAD

**Issue by UvarovBoris** [kotcrab/VisEditor#89]
Hi, I  have 2 directories in atlas dir: "level" and "UI". In "level" i have pack_level.atlas, in "UI" I have pack_UI.atlas. But VisEditor cant open its with message "Unknown error encountered during atlas loading". If atlases in parent directory "atlas" VisEditor can open its.  
Version of VisEditor is 2.6.0-SNAPSHOT 20151112

**Comment by kotcrab** [comment]
Fixed, thanks! New snapshot is being built.
