### ISSUE TITLE
Text in TextArea not visible when using SkinScale.X2

### ISSUE THREAD

**Issue by nchuck** [kotcrab/VisEditor#92]
![image](https://cloud.githubusercontent.com/assets/4037632/11733769/9a2ce84e-9f76-11e5-9155-284f7a3cb607.png)

I don't think it needs further explanation.

All I do to set the scale is use this:
```java
        if(Gdx.app.getType() == Application.ApplicationType.Desktop)
            VisUI.load(VisUI.SkinScale.X1);
        else
            VisUI.load(VisUI.SkinScale.X2);
```

I don't think it affects it in some weird way.

**Comment by kotcrab** [comment]
Works fine in VisUI test app. Please provide [SSCCE](http://sscce.org/).

**Comment by nchuck** [comment]
Sorry, been out for a while, will deliver when I get home today at night

**Comment by kotcrab** [comment]
I noticed another issue in your screenshot: TabbedPane Tab close button was too small, I fixed it.

Still waiting for SSCCE for TextArea.

**Comment by kotcrab** [comment]
Closing as no SSCCE was provided and this issue can't be reproduced using VisUI 1.0.0 test application.
